# Generated by Django 4.0.5 on 2022-06-03 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200, unique=True)),
                ('post_content', models.TextField()),
                ('post_image', models.ImageField(upload_to='blog_pic')),
                ('post_push_date', models.DateTimeField(auto_now=True)),
                ('post_last_updated', models.DateTimeField(auto_now=True)),
                ('post_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userprofile')),
            ],
        ),
    ]
