# Generated by Django 4.0.5 on 2022-06-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_post_image_alter_post_post_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='media/profile_pic/2.jpg', upload_to='blog_pic'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
