# Generated by Django 4.0.5 on 2022-06-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_comment_count_post_post_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_comment_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
