# Generated by Django 4.0.5 on 2022-06-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_post_comment_count_alter_post_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postview',
            name='blog',
        ),
        migrations.AddField(
            model_name='post',
            name='post_like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='PostView',
        ),
    ]
